# Generated by Django 5.2.10 on 2026-02-19 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0006_medico_firma_medico_sello'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examenes_solicitados', models.TextField(verbose_name='Exámenes')),
                ('otros', models.CharField(blank=True, max_length=200, null=True, verbose_name='Otros Exámenes')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones / Nota')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Realizado', 'Realizado')], default='Pendiente', max_length=20)),
                ('resultados_archivo', models.FileField(blank=True, null=True, upload_to='resultados_lab/')),
                ('fecha_resultado', models.DateTimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_lab', to='administracion.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='administracion.paciente')),
            ],
        ),
    ]
