# Generated by Django 5.2.10 on 2026-02-20 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_medico_firma_medico_sello'),
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudexamen',
            name='cedula_paciente',
            field=models.CharField(default=1, max_length=30, verbose_name='Cédula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudexamen',
            name='nombre_paciente',
            field=models.CharField(default=1, max_length=150, verbose_name='Nombre del Paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudexamen',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_lab', to='administracion.paciente'),
        ),
    ]
