# Generated by Django 5.2.10 on 2026-04-01 02:34

import laboratorio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_solicitudexamen_cedula_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudexamen',
            name='resultados_archivo',
            field=models.FileField(blank=True, null=True, upload_to=laboratorio.models.renombrar_archivo_seguro),
        ),
    ]
