# Generated by Django 5.2.10 on 2026-04-10 03:12

import django.db.models.deletion
import laboratorio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_medicamento_codigo_barras_alter_ordenfarmacia_medico'),
        ('laboratorio', '0003_alter_solicitudexamen_resultados_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudexamen',
            name='resultados_archivo',
            field=models.FileField(blank=True, null=True, upload_to=laboratorio.models.renombrar_archivo_seguro, verbose_name='Documento de Resultados (Opcional)'),
        ),
        migrations.CreateModel(
            name='ExamenCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Examen (Ej: Hematología Completa)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Indicaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Disponible en Laboratorio')),
                ('cantidad_reactivo', models.PositiveIntegerField(default=1, verbose_name='Cantidad a descontar por prueba')),
                ('reactivo_necesario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.medicamento', verbose_name='Reactivo a descontar (Farmacia)')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Parámetro (Ej: Hemoglobina, Glucosa)')),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad (Ej: g/dL, mg/dL)')),
                ('rango_minimo', models.FloatField(blank=True, null=True, verbose_name='Valor Mínimo Normal')),
                ('rango_maximo', models.FloatField(blank=True, null=True, verbose_name='Valor Máximo Normal')),
                ('valor_referencia_texto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia en Texto')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='laboratorio.examencatalogo')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_obtenido', models.CharField(max_length=100, verbose_name='Valor Obtenido')),
                ('es_anormal', models.BooleanField(default=False, verbose_name='¿Fuera de Rango?')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_estructurados', to='laboratorio.solicitudexamen')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.parametroexamen')),
            ],
        ),
    ]
