# Generated by Django 5.2.10 on 2026-04-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_alter_solicitudexamen_resultados_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudexamen',
            name='correo_paciente',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo para enviar resultados'),
        ),
    ]
