# Generated by Django 5.2.10 on 2026-04-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_solicitudexamen_correo_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudexamen',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Realizado', 'Realizado'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
