# Generated by Django 5.2.10 on 2026-05-04 05:28

import core.validators
import laboratorio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_alter_solicitudexamen_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudexamen',
            name='resultados_archivo',
            field=models.FileField(blank=True, null=True, upload_to=laboratorio.models.renombrar_archivo_seguro, validators=[core.validators.validar_imagen_o_pdf], verbose_name='Documento de Resultados (Opcional)'),
        ),
    ]
