# Generated by Django 5.2.10 on 2026-02-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_paciente_direccion_paciente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='cm',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Colegio Médico'),
        ),
        migrations.AddField(
            model_name='medico',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles_medicos/'),
        ),
    ]
