# Generated by Django 5.2.10 on 2026-02-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_medico_cm_medico_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_medicos/'),
        ),
        migrations.AddField(
            model_name='medico',
            name='sello',
            field=models.ImageField(blank=True, null=True, upload_to='sellos_medicos/'),
        ),
    ]
