# Generated by Django 5.2.10 on 2026-03-17 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_factura_detallefactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cedula_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula (Paciente de Paso)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre (Paciente de Paso)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='administracion.paciente'),
        ),
    ]
