# Generated by Django 5.2.10 on 2026-04-01 02:30

import administracion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_factura_cedula_cliente_factura_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to=administracion.models.renombrar_archivo_seguro),
        ),
        migrations.AlterField(
            model_name='medico',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=administracion.models.renombrar_archivo_seguro),
        ),
        migrations.AlterField(
            model_name='medico',
            name='sello',
            field=models.ImageField(blank=True, null=True, upload_to=administracion.models.renombrar_archivo_seguro),
        ),
    ]
