# Generated by Django 5.2.10 on 2026-04-18 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_alter_medico_firma_alter_medico_foto_perfil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('Consulta', 'Consulta Médica'), ('Laboratorio', 'Laboratorio'), ('Imagenologia', 'Rayos X / Eco'), ('Enfermeria', 'Servicios de Enfermería'), ('Otro', 'Otro')], max_length=50)),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('Efectivo USD', 'Efectivo USD'), ('Zelle', 'Zelle'), ('Efectivo Bs', 'Efectivo Bs'), ('Pago Movil', 'Pago Móvil'), ('Punto de Venta', 'Punto de Venta')], max_length=50)),
                ('monto_moneda_original', models.DecimalField(decimal_places=2, help_text='Lo que entregó el px (Bs o USD)', max_digits=15)),
                ('monto_equivalente_usd', models.DecimalField(decimal_places=2, help_text='El valor que representa en la factura', max_digits=15)),
                ('referencia', models.CharField(blank=True, help_text='Nro de recibo o Zelle', max_length=100, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='administracion.factura')),
            ],
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('tasa_bcv_dia', models.DecimalField(decimal_places=2, help_text='Tasa fijada al abrir la caja', max_digits=10)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=20)),
                ('total_usd_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_zelle', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_bs_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_pago_movil', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_punto_venta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
