# Generated by Django 5.2.10 on 2026-04-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_catalogoservicio_pagofactura_sesioncaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
