# Generated by Django 5.2.10 on 2026-05-04 05:28

import administracion.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_paciente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to=administracion.models.renombrar_archivo_seguro, validators=[core.validators.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=administracion.models.renombrar_archivo_seguro, validators=[core.validators.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='sello',
            field=models.ImageField(blank=True, null=True, upload_to=administracion.models.renombrar_archivo_seguro, validators=[core.validators.validar_imagen]),
        ),
    ]
