# Generated by Django 5.2.10 on 2026-06-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Sala', 'En Sala'), ('Atendido', 'Atendido')], default='Pendiente', max_length=20),
        ),
    ]
