# Generated by Django 5.2.10 on 2026-03-30 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0008_factura_cedula_cliente_factura_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo de Sangre')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias Conocidas')),
                ('antecedentes_personales', models.TextField(blank=True, null=True, verbose_name='Antecedentes Personales')),
                ('antecedentes_familiares', models.TextField(blank=True, null=True, verbose_name='Antecedentes Familiares')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expediente_medico', to='administracion.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('tension_arterial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tensión Arterial')),
                ('frecuencia_cardiaca', models.CharField(blank=True, max_length=10, null=True, verbose_name='FC')),
                ('frecuencia_respiratoria', models.CharField(blank=True, max_length=10, null=True, verbose_name='FR')),
                ('temperatura', models.CharField(blank=True, max_length=10, null=True, verbose_name='Temp')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso')),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Talla')),
                ('saturacion_oxigeno', models.CharField(blank=True, max_length=10, null=True, verbose_name='SatO2 (%)')),
                ('glicemia', models.CharField(blank=True, max_length=10, null=True, verbose_name='GLIC (mg/dl)')),
                ('motivo_consulta', models.TextField(blank=True, null=True, verbose_name='Motivo de Consulta')),
                ('enfermedad_actual', models.TextField(blank=True, null=True, verbose_name='Enfermedad Actual')),
                ('examen_fisico', models.TextField(blank=True, null=True, verbose_name='Examen Físico Completo')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('plan_tratamiento', models.TextField(blank=True, null=True, verbose_name='Plan / Tratamiento')),
                ('tipo_anexo', models.CharField(blank=True, choices=[('Lab', 'Laboratorio'), ('Img', 'Imagenología'), ('Otro', 'Otro')], max_length=10, null=True)),
                ('archivo_anexo', models.ImageField(blank=True, null=True, upload_to='anexos_historias/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.cita')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.medico')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='medico.expedientebase')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medicamentos', models.TextField()),
                ('indicaciones', models.TextField()),
                ('nombre_paciente', models.CharField(blank=True, max_length=150, null=True)),
                ('cedula_paciente', models.CharField(blank=True, max_length=20, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.medico')),
            ],
        ),
    ]
