# Generated by Django 5.2.10 on 2026-04-01 02:25

import medico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaevolucion',
            name='archivo_anexo',
            field=models.ImageField(blank=True, null=True, upload_to=medico.models.renombrar_archivo_seguro),
        ),
    ]
