# Generated by Django 5.2.10 on 2026-04-08 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_alter_medico_firma_alter_medico_foto_perfil_and_more'),
        ('medico', '0002_alter_consultaevolucion_archivo_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstanciaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('motivo_texto', models.TextField(verbose_name='Texto de la Constancia')),
                ('codigo_verificacion', models.CharField(blank=True, max_length=15, unique=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.paciente')),
            ],
        ),
    ]
