# Generated by Django 5.2.10 on 2026-05-04 05:28

import core.validators
import medico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_constanciamedica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaevolucion',
            name='archivo_anexo',
            field=models.ImageField(blank=True, null=True, upload_to=medico.models.renombrar_archivo_seguro, validators=[core.validators.validar_imagen]),
        ),
    ]
