# Generated by Django 5.2.10 on 2026-06-19 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0022_cita_es_control'),
        ('medico', '0004_alter_consultaevolucion_archivo_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='administracion.paciente'),
        ),
    ]
