# Generated by Django 5.2.10 on 2026-02-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='firma_digital',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_medicos/', verbose_name='Sello y Firma'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mpss',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MPSS / Matrícula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=0, max_length=20, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
