# Generated by Django 5.2.10 on 2026-02-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_especialidad_usuario_firma_digital_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='mpss',
            new_name='mpps',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Colegio Médico (CM)'),
        ),
    ]
