# Generated by Django 5.2.10 on 2026-02-18 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_mpss_usuario_mpps_usuario_cm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='firma_digital',
        ),
    ]
