# Generated by Django 5.2.10 on 2026-02-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0006_medico_firma_medico_sello'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Medicamento')),
                ('concentracion', models.CharField(help_text='Ej. 500mg, 10ml', max_length=50)),
                ('presentacion', models.CharField(help_text='Ej. Tabletas, Jarabe, Ampollas', max_length=50)),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('stock_minimo', models.IntegerField(default=10, verbose_name='Stock Mínimo de Alerta')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
                ('receta_medica_texto', models.TextField(blank=True, null=True, verbose_name='Indicaciones del Médico')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Despachado', 'Despachado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_farmacia', to='administracion.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.medicamento')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='farmacia.ordenfarmacia')),
            ],
        ),
    ]
