# Generated by Django 5.2.10 on 2026-02-24 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_medico_firma_medico_sello'),
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenfarmacia',
            name='cedula_paciente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula (No registrado)'),
        ),
        migrations.AddField(
            model_name='ordenfarmacia',
            name='nombre_paciente',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre (No registrado)'),
        ),
        migrations.AlterField(
            model_name='ordenfarmacia',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_farmacia', to='administracion.paciente'),
        ),
    ]
