# Generated by Django 5.2.10 on 2026-03-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_ordenfarmacia_cedula_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, verbose_name='Número de Lote')),
                ('cantidad_ingresada', models.PositiveIntegerField(verbose_name='Cantidad Inicial')),
                ('cantidad_actual', models.PositiveIntegerField(verbose_name='Stock Disponible en Lote')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='farmacia.medicamento')),
            ],
        ),
    ]
