# Generated by Django 5.2.10 on 2026-04-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_lotemedicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Información extra del medicamento', null=True, verbose_name='Descripción / Laboratorio'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos/', verbose_name='Foto del Medicamento'),
        ),
    ]
