# Generated by Django 5.2.10 on 2026-04-04 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_medicamento_descripcion_medicamento_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada (Nuevo Lote)'), ('SALIDA', 'Salida (Despacho)'), ('DEVOLUCION', 'Devolución al Inventario'), ('AJUSTE', 'Ajuste Manual / Merma')], max_length=20)),
                ('cantidad', models.IntegerField(help_text='Cantidad sumada o restada')),
                ('stock_resultante', models.IntegerField(help_text='Stock físico después de este movimiento')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(help_text='Ej: Lote #123, Orden #45, Motivo de ajuste', max_length=255)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_kardex', to='farmacia.medicamento')),
                ('orden_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_asociados', to='farmacia.ordenfarmacia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
