# Generated by Django 5.2.10 on 2026-04-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='es_controlado',
            field=models.BooleanField(default=False, help_text='Requiere validación estricta de récipe para su despacho.', verbose_name='¿Es Psicotrópico/Controlado?'),
        ),
    ]
