# Generated by Django 5.2.10 on 2026-04-05 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_alter_medico_firma_alter_medico_foto_perfil_and_more'),
        ('farmacia', '0006_medicamento_es_controlado'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='ordenfarmacia',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.medico'),
        ),
    ]
