# Generated by Django 5.2.10 on 2026-05-04 05:27

import core.validators
import django.db.models.deletion
import farmacia.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_medicamento_codigo_barras_alter_ordenfarmacia_medico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=farmacia.models.renombrar_archivo_seguro, validators=[core.validators.validar_imagen], verbose_name='Foto del Medicamento'),
        ),
        migrations.CreateModel(
            name='AuditoriaControlado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=150)),
                ('cedula_paciente', models.CharField(max_length=20)),
                ('cantidad_despachada', models.PositiveIntegerField()),
                ('stock_antes', models.IntegerField()),
                ('stock_despues', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='farmacia.medicamento')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_controlados', to='farmacia.ordenfarmacia')),
                ('usuario_despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Controlado',
                'verbose_name_plural': 'Auditorías de Controlados',
                'ordering': ['-timestamp'],
            },
        ),
    ]
