# Generated by Django 5.2.10 on 2026-05-04 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0008_alter_medicamento_foto_auditoriacontrolado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriacontrolado',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_controlados', to='farmacia.ordenfarmacia'),
        ),
    ]
